easy_admin:
    site_name: 'Gestion de ma coPro'
    user:
        display_name: true
        display_avatar: false
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Articles' }
            - { entity: 'Articles', label: 'Articles', icon: 'book' }
            - { label: 'Utilisateurs' }
            - { entity: 'Users', label: 'Utilisateurs', icon: 'user' }
    formats:
        datetime: 'd/m/Y à H:i'
    entities:
        Articles:
            class: App\Entity\Articles
            list:
                fields:
                    - id
                    - titre
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
                    - { property: 'created_at', label: 'Créé' }
                sort: ['created_at', 'desc']
            form:
                fields:
                    - titre
                    - { property: 'contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - users
        Users:
            class: App\Entity\Users
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - email
                    - { property: 'roles', label: 'Rôles', type: json_array}
            form:
                fields:
                    - email
                    - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
