easy_admin:
    site_name: 'Gestion de ma coPro' 
    user:
        display_name: true
        display_avatar: true
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Accueil du site', route: 'infos_articles', icon: 'home' }
            - { label: 'Articles' }
            - { entity: 'Articles', label: 'Articles', icon: 'file' }
            - { entity: 'Commentaires', label: 'Commentaires', icon: 'comment' }
            - { label: 'Proprietaires' }
            - { entity: 'Proprietaires', label: 'Propriétaires', icon: 'users' }
            - { label: 'Utilisateurs' }
            - { entity: 'Users', label: 'Utilisateurs', icon: 'user' }           
    formats:
        datetime: 'd/m/Y à H:i'
    entities:
        Articles:
            class: App\Entity\Articles
            list:
                fields:
                    - id
                    - titre
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
                    - { property: 'created_at', label: 'Créé' }
                sort: ['created_at', 'desc']
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.featured_images%' }
            form:
                fields:
                    - titre
                    - { property: 'contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - users
        Commentaires:
            class: App\Entity\Commentaires
            list:
                fields:
                    - actif
                    - pseudo
                    - email
                    - contenu
                    - { property: 'created_at', label: 'Créé' }
                sort: ['created_at', 'desc']
            form:
                fields:
                    - pseudo
                    - email
                    - { property: 'contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    - { property: 'created_at', label: 'Créé' }
                sort: ['created_at', 'desc']
        Proprietaires:
            class: App\Entity\Proprietaires
            list:
                fields:
                    - nom
                    - prenom
                    - numero
                    - voie
                    - codePostal
                    - ville
                    - telperso
                    - telPro
                    - mail
                    - bic
                    - iban
                sort: ['id', 'desc']
            form:
                fields:
                    - nom
                    - prenom
                    - numero
                    - voie
                    - codePostal
                    - ville
                    - telPerso
                    - telPro
                    - mail
                    - bic
                    - iban
        Users:
            class: App\Entity\Users
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - email
                    - { property: 'roles', label: 'Rôles', type: json_array}
            form:
                fields:
                    - email
                    - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
